import type { TechnologyObservable, TechnologyObservableId } from './types';

export const TECHNOLOGY_OBSERVABLES: Record<TechnologyObservableId, TechnologyObservable> = {
  antigravity_lift: {
    id: 'antigravity_lift',
    code: 'TO-1',
    label: 'Anti-Gravity Lift',
    description: 'Object appears to overcome gravitational force without conventional propulsion — no wings, rotors, exhaust, or visible means of lift.',
    scientificBasis: 'Violation of Newtonian mechanics and known aerodynamic principles. No known human technology achieves sustained hover without downwash, exhaust, or electromagnetic support at observed scales.',
    detectionSignals: [
      'Sustained hover with no visible propulsion',
      'No downwash or ground effect disturbance',
      'No exhaust or thermal signature from propulsion',
      'Object mass inconsistent with buoyant lift',
      'Silent operation during hover',
    ],
    methods: [
      'FLIR/IR imaging for thermal signatures',
      'Doppler radar for relative velocity confirmation',
      'Ground-level pressure sensors for downwash detection',
      'Acoustic monitoring for propulsion noise',
      'Witness triangulation for altitude confirmation',
    ],
    references: [
      'Elizondo, "The Five Observables" framework, AATIP (anti-gravity lift)',
      'Knuth et al., "Estimating Flight Characteristics of Anomalous Unidentified Aerial Vehicles," Entropy, 2019',
    ],
  },
  instantaneous_acceleration: {
    id: 'instantaneous_acceleration',
    code: 'TO-2',
    label: 'Instantaneous Acceleration',
    description: 'Object accelerates at rates far beyond known aerospace capabilities — estimated hundreds or thousands of g-forces with no apparent inertial effects.',
    scientificBasis: 'Exceeds structural limits of known materials and biological tolerance. F/A-18 max sustained: ~9g. In the 2004 Nimitz encounter, SCU forensic analysis estimated UAP accelerations from 40g to hundreds of g, with some maneuver estimates reaching thousands of g (Knuth et al., 2019).',
    detectionSignals: [
      'Radar track showing extreme velocity change over minimal time',
      'Object transitions from hover to hypersonic in < 1 second',
      'Right-angle or acute-angle turns at high speed',
      'Immediate reversal of travel direction',
      'No observed structural deformation during maneuver',
    ],
    methods: [
      'Multi-radar track correlation for velocity profiles',
      'Frame-by-frame video analysis for acceleration curves',
      'Radar Doppler shift measurements',
      'Satellite track data for independent velocity confirmation',
      'Accelerometer data from nearby sensor platforms',
    ],
    references: [
      'Powell et al., "A Forensic Analysis of Navy Carrier Strike Group Eleven\'s Encounter with an Anomalous Aerial Vehicle," SCU, 2019',
      'Knuth et al., "Estimating Flight Characteristics of Anomalous Unidentified Aerial Vehicles," Entropy, 2019',
    ],
  },
  hypersonic_no_signatures: {
    id: 'hypersonic_no_signatures',
    code: 'TO-3',
    label: 'Hypersonic Velocities Without Signatures',
    description: 'Object achieves hypersonic speeds (Mach 5+) without producing sonic boom, heat signature, or plasma sheath — violating known atmospheric physics.',
    scientificBasis: 'Objects exceeding Mach 1 in atmosphere must produce shock waves (sonic boom). Hypersonic flight generates extreme adiabatic heating and plasma formation. Absence of these signatures implies either non-atmospheric medium interaction or unknown physics.',
    detectionSignals: [
      'Radar-confirmed velocity exceeding Mach 5',
      'No sonic boom detected at ground level',
      'No IR bloom or thermal wake',
      'No plasma sheath visible in optical/UV spectrum',
      'No atmospheric disturbance trail',
    ],
    methods: [
      'Phased-array radar for precise speed measurement',
      'Infrasound sensors for sonic boom detection',
      'Multi-spectral imaging for plasma detection',
      'Seismographic stations for shock wave detection',
      'FLIR for thermal signature analysis',
    ],
    references: [
      'Anderson, "Fundamentals of Aerodynamics," McGraw-Hill (hypersonic regime physics)',
      'Elizondo, "The Five Observables" framework, AATIP (hypersonic velocities without signatures)',
    ],
  },
  low_observability: {
    id: 'low_observability',
    code: 'TO-4',
    label: 'Low Observability',
    description: 'Object evades or confounds multiple sensor modalities simultaneously — radar, infrared, visual, or electromagnetic detection systems fail to maintain consistent track.',
    scientificBasis: 'Known stealth technology reduces radar cross-section through geometry and materials but cannot simultaneously defeat all sensor modalities. UAP cases show simultaneous radar evasion, IR suppression, and visual cloaking beyond current technology.',
    detectionSignals: [
      'Intermittent radar returns despite visual confirmation',
      'Radar track acquisition followed by unexplained loss',
      'Sensor malfunction coinciding with proximity',
      'Object visible to one modality but not others',
      'Electronic warfare effects without identifiable source',
    ],
    methods: [
      'Multi-sensor correlation (radar + IR + EO)',
      'Radar cross-section estimation',
      'EM spectrum analysis for jamming signatures',
      'Sensor diagnostic logs for malfunction patterns',
      'Signal-to-noise analysis across detection systems',
    ],
    references: [
      'USS Princeton (AN/SPY-1 Aegis radar) operator testimony, 2004 Nimitz encounter',
      'Elizondo, "The Five Observables" framework, AATIP (low observability)',
    ],
  },
  transmedium_travel: {
    id: 'transmedium_travel',
    code: 'TO-5',
    label: 'Transmedium Travel',
    description: 'Object transitions between air, water, and/or space without apparent structural reconfiguration, speed loss, or medium-transition effects.',
    scientificBasis: 'Air-to-water transition requires extreme structural adaptation (different pressure regimes, Reynolds numbers, propulsion requirements). No known vehicle operates effectively across multiple media without reconfiguration.',
    detectionSignals: [
      'Object observed entering water from air without splash proportional to size/speed',
      'Object observed exiting water into air with continued controlled flight',
      'Sonar track correlating with aerial radar track',
      'No deceleration during medium transition',
      'Consistent shape/size across media transitions',
    ],
    methods: [
      'Coordinated air/maritime sensor monitoring',
      'Sonar-to-radar track handoff correlation',
      'High-speed camera for transition dynamics',
      'Underwater hydrophone arrays',
      'Satellite IR for ocean surface thermal anomalies',
    ],
    references: [
      'Scientific Coalition for UAP Studies, "2013 Aguadilla Puerto Rico: The Detailed Analysis of an Unidentified Anomalous Phenomenon Captured by the Department of Homeland Security," 2015',
      'Gallaudet, "Beneath the Surface," The Sol Foundation, 2023',
    ],
  },
  biological_effects: {
    id: 'biological_effects',
    code: 'TO-6',
    label: 'Biological Effects',
    description: 'Proximity to the object causes measurable radiological, energetic, or physiological effects on biological organisms — burns, nausea, cellular damage, or other medical sequelae.',
    scientificBasis: 'Consistent with high-energy electromagnetic radiation exposure. AAWSAP/BAASS documented cases with radiation-like injuries. Colares, Brazil (1977) documented beam-related injuries on dozens of witnesses.',
    detectionSignals: [
      'Radiation-type burns without identifiable source',
      'Nausea, headaches, or disorientation in proximity',
      'Skin lesions or erythema post-encounter',
      'Cellular or DNA damage documented in medical records',
      'Multiple witnesses reporting similar physiological effects',
      'Vegetation damage patterns around landing sites',
    ],
    methods: [
      'Medical examination and documentation',
      'Dosimetry and radiation survey at site',
      'Blood panel and cellular analysis',
      'Vegetation and soil sample analysis',
      'Geiger counter readings at encounter locations',
      'Long-term medical follow-up of exposed individuals',
    ],
    references: [
      'Lacatski, Kelleher & Knapp, "Skinwalkers at the Pentagon," 2021 (AAWSAP medical cases)',
      'Operação Prato (Operation Saucer) medical documentation, Brazilian Air Force, Colares, 1977',
    ],
  },
};
