import type { OCSNode } from './types';

export const OCS_TAXONOMY: readonly OCSNode[] = [
  // ============================================================
  // DOMAIN 1.0 — PHYSICAL
  // ============================================================
  {
    id: '1',
    label: 'Physical',
    description: 'Theories attributing UAP to tangible, material objects or phenomena.',
    domain: 'physical',
    depth: 0,
    parentId: null,
    children: ['1.1', '1.2', '1.3'],
    scientificallyTestable: true,
  },

  // --- 1.1 Intradimensional ---
  {
    id: '1.1',
    label: 'Intradimensional',
    description: 'Manifestations from dimensions/realms within our own physical reality.',
    domain: 'physical',
    depth: 1,
    parentId: '1',
    children: ['1.1.1', '1.1.2', '1.1.3'],
    scientificallyTestable: true,
  },

  // 1.1.1 Prosaic
  {
    id: '1.1.1',
    label: 'Prosaic',
    description: 'Ordinary or conventional explanations for observed phenomena.',
    domain: 'physical',
    depth: 2,
    parentId: '1.1',
    children: ['1.1.1.1', '1.1.1.2'],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.1',
    label: 'Natural',
    description: 'Atmospheric, celestial, or geological phenomena misidentified as anomalous.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.1',
    children: ['1.1.1.1.1', '1.1.1.1.2', '1.1.1.1.3', '1.1.1.1.4'],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.1.1',
    label: 'Optical Artifact / Illusion',
    description: 'Lens flares, reflections, mirages, temperature inversions, or other optical effects.',
    domain: 'physical',
    depth: 4,
    parentId: '1.1.1.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.1.2',
    label: 'Celestial',
    description: 'Stars, planets, meteors, satellites, or space debris misidentified.',
    domain: 'physical',
    depth: 4,
    parentId: '1.1.1.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.1.3',
    label: 'Meteorological',
    description: 'Ball lightning, lenticular clouds, sprites, or other atmospheric phenomena.',
    domain: 'physical',
    depth: 4,
    parentId: '1.1.1.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.1.4',
    label: 'Geophysical',
    description: 'Earthquake lights, piezoelectric effects, or volcanic phenomena.',
    domain: 'physical',
    depth: 4,
    parentId: '1.1.1.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.2',
    label: 'Human',
    description: 'Human activities or technologies misidentified as anomalous.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.1',
    children: ['1.1.1.2.1', '1.1.1.2.2', '1.1.1.2.3', '1.1.1.2.4'],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.2.1',
    label: 'Governmental',
    description: 'Military aircraft, drones, or test vehicles from known government programs.',
    domain: 'physical',
    depth: 4,
    parentId: '1.1.1.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.2.2',
    label: 'Extra-Governmental',
    description: 'Black budget programs, Special Access Programs (SAPs), or unacknowledged projects.',
    domain: 'physical',
    depth: 4,
    parentId: '1.1.1.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.2.3',
    label: 'Inter-governmental',
    description: 'Foreign adversary technology or multinational classified programs.',
    domain: 'physical',
    depth: 4,
    parentId: '1.1.1.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.1.2.4',
    label: 'Private / Commercial',
    description: 'Commercial drones, private aerospace ventures, or civilian technology.',
    domain: 'physical',
    depth: 4,
    parentId: '1.1.1.2',
    children: [],
    scientificallyTestable: true,
  },

  // 1.1.2 Cryptoterrestrial
  {
    id: '1.1.2',
    label: 'Cryptoterrestrial',
    description: 'Hidden Earth-based civilizations or entities operating outside known history.',
    domain: 'physical',
    depth: 2,
    parentId: '1.1',
    children: ['1.1.2.1', '1.1.2.2', '1.1.2.3', '1.1.2.4'],
    scientificallyTestable: true,
    aliases: ['CTH'],
  },
  {
    id: '1.1.2.1',
    label: 'Ancient / Proto-Human Survival',
    description: 'Remnant populations of earlier hominid species or ancient civilizations that survived in isolation.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.2.2',
    label: 'Breakaway Civilization',
    description: 'Human splinter groups that developed advanced technology in secret.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.2.3',
    label: 'Cryptids / Humanoids',
    description: 'Non-human intelligent entities indigenous to Earth but outside the known tree of life.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.2.4',
    label: 'Stranded "Gods"',
    description: 'Entities from ancient mythological accounts interpreted as literal stranded visitors.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.2',
    children: [],
    scientificallyTestable: true,
  },

  // 1.1.3 Extraterrestrial
  {
    id: '1.1.3',
    label: 'Extraterrestrial',
    description: 'Intelligence visiting from other locations in spacetime.',
    domain: 'physical',
    depth: 2,
    parentId: '1.1',
    children: ['1.1.3.1', '1.1.3.2', '1.1.3.3', '1.1.3.4'],
    scientificallyTestable: true,
    aliases: ['ETH'],
  },
  {
    id: '1.1.3.1',
    label: 'Solar System',
    description: 'Intelligence originating from elsewhere in our solar system.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.3.2',
    label: 'Interstellar',
    description: 'Intelligence from other star systems within our galaxy.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.3.3',
    label: 'Intergalactic',
    description: 'Intelligence from other galaxies.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.1.3.4',
    label: 'Unknown Region of Space-Time',
    description: 'Intelligence from an uncharacterized region of our physical universe.',
    domain: 'physical',
    depth: 3,
    parentId: '1.1.3',
    children: [],
    scientificallyTestable: true,
  },

  // --- 1.2 Extradimensional ---
  {
    id: '1.2',
    label: 'Extradimensional',
    description: 'UAPs from other dimensions, parallel universes, or realms beyond our physical reality.',
    domain: 'physical',
    depth: 1,
    parentId: '1',
    children: ['1.2.1', '1.2.2'],
    scientificallyTestable: true,
  },
  {
    id: '1.2.1',
    label: '3-D Entity From Hyperspace',
    description: 'Entities projecting into our 3+1 dimensional spacetime from higher dimensions.',
    domain: 'physical',
    depth: 2,
    parentId: '1.2',
    children: ['1.2.1.1', '1.2.1.2', '1.2.1.3'],
    scientificallyTestable: true,
  },
  {
    id: '1.2.1.1',
    label: 'Compactified Dimensions',
    description: 'Entities from string theory / Kaluza-Klein compactified extra dimensions.',
    domain: 'physical',
    depth: 3,
    parentId: '1.2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.2.1.2',
    label: 'Hyperspace "Bulk"',
    description: 'Entities from the bulk space of Randall-Sundrum brane models.',
    domain: 'physical',
    depth: 3,
    parentId: '1.2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.2.1.3',
    label: 'Disconnected Hyperspace',
    description: 'Entities from higher-dimensional spaces not connected to our brane.',
    domain: 'physical',
    depth: 3,
    parentId: '1.2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2',
    label: 'Hyper-D "Brane"',
    description: 'Brane interactions from string/M-theory producing observable effects.',
    domain: 'physical',
    depth: 2,
    parentId: '1.2',
    children: ['1.2.2.1', '1.2.2.2'],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2.1',
    label: 'Projection / "Shadow"',
    description: 'Lower-dimensional projections of higher-dimensional objects.',
    domain: 'physical',
    depth: 3,
    parentId: '1.2.2',
    children: ['1.2.2.1.1', '1.2.2.1.2', '1.2.2.1.3'],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2.1.1',
    label: '0-to-2 Dimensional',
    description: 'Point or plane-like projections from higher dimensions.',
    domain: 'physical',
    depth: 4,
    parentId: '1.2.2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2.1.2',
    label: '3-Dimensional',
    description: 'Full volumetric projections appearing as solid objects.',
    domain: 'physical',
    depth: 4,
    parentId: '1.2.2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2.1.3',
    label: 'Fractal Dimensional',
    description: 'Non-integer dimensional projections with fractal geometry.',
    domain: 'physical',
    depth: 4,
    parentId: '1.2.2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2.2',
    label: '≤ 3-D "Avatar"',
    description: 'Controlled projections or constructs operating as proxies.',
    domain: 'physical',
    depth: 3,
    parentId: '1.2.2',
    children: ['1.2.2.2.1', '1.2.2.2.2', '1.2.2.2.3'],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2.2.1',
    label: 'Hologram / "Telepresence"',
    description: 'Remote presence via holographic or light-based projection.',
    domain: 'physical',
    depth: 4,
    parentId: '1.2.2.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2.2.2',
    label: 'Automaton',
    description: 'Self-operating mechanical or energetic construct.',
    domain: 'physical',
    depth: 4,
    parentId: '1.2.2.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.2.2.2.3',
    label: 'Artificial Lifeform',
    description: 'Engineered biological or hybrid entity operating as a proxy.',
    domain: 'physical',
    depth: 4,
    parentId: '1.2.2.2',
    children: [],
    scientificallyTestable: true,
  },

  // --- 1.3 Interdimensional ---
  {
    id: '1.3',
    label: 'Interdimensional',
    description: 'UAPs traversing between different dimensions or realities.',
    domain: 'physical',
    depth: 1,
    parentId: '1',
    children: ['1.3.1', '1.3.2', '1.3.3'],
    scientificallyTestable: true,
  },
  {
    id: '1.3.1',
    label: 'Multiverse',
    description: 'Entities or phenomena crossing between parallel universes.',
    domain: 'physical',
    depth: 2,
    parentId: '1.3',
    children: ['1.3.1.1', '1.3.1.2', '1.3.1.3', '1.3.1.4'],
    scientificallyTestable: true,
  },
  {
    id: '1.3.1.1',
    label: 'Portal / Wormhole',
    description: 'Traversal via Einstein-Rosen bridges or manufactured gateways.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.1.2',
    label: 'Colliding Universe(s)',
    description: 'Phenomena from brane collision events (ekpyrotic cosmology).',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.1.3',
    label: 'Parallel Universe(s)',
    description: 'Entities from parallel but non-interacting universe branches.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.1.4',
    label: 'QFT "Many Worlds"',
    description: 'Quantum-mechanical many-worlds interpretation producing observable crossover.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.2',
    label: 'Time Travel',
    description: 'Entities or vehicles traversing temporal dimensions.',
    domain: 'physical',
    depth: 2,
    parentId: '1.3',
    children: ['1.3.2.1', '1.3.2.2', '1.3.2.3', '1.3.2.4', '1.3.2.5'],
    scientificallyTestable: true,
  },
  {
    id: '1.3.2.1',
    label: 'Humans From Future',
    description: 'Time-traveling humans from our future timeline.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.2.2',
    label: 'Humans From Past',
    description: 'Time-traveling humans from our past (advanced pre-history).',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.2.3',
    label: 'Humans From Alternate Timeline',
    description: 'Humans from divergent timeline branches.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.2.4',
    label: 'Non-Human Entity',
    description: 'Non-human intelligence traversing time dimensions.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.2.5',
    label: 'Additional Time Dimension(s)',
    description: 'Traversal via hypothetical extra temporal dimensions beyond our single time axis.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.3',
    label: 'Scale Invariance',
    description: 'Phenomena emerging from scale-dependent physics or quantum-cosmological effects.',
    domain: 'physical',
    depth: 2,
    parentId: '1.3',
    children: ['1.3.3.1', '1.3.3.2', '1.3.3.3', '1.3.3.4', '1.3.3.5'],
    scientificallyTestable: true,
  },
  {
    id: '1.3.3.1',
    label: 'Macro Quantum Fluctuation',
    description: 'Macroscopic manifestation of quantum vacuum fluctuations.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.3.2',
    label: 'Distance Recursion',
    description: 'Self-similar structure at different scales producing observable anomalies.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.3.3',
    label: 'Pan-Galactic Entanglement',
    description: 'Non-local quantum entanglement effects at galactic scales.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.3.4',
    label: 'Unobserved "Vibratory Modes"',
    description: 'Hidden vibrational modes of spacetime not yet detected by instruments.',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '1.3.3.5',
    label: 'Conformal Cyclic Cosmology',
    description: 'Signals or entities from previous cosmic aeons (Penrose CCC).',
    domain: 'physical',
    depth: 3,
    parentId: '1.3.3',
    children: [],
    scientificallyTestable: true,
  },

  // ============================================================
  // DOMAIN 2.0 — PSYCHOSOCIAL
  // ============================================================
  {
    id: '2',
    label: 'Psychosocial',
    description: 'Theories attributing UAP to psychological, perceptual, and sociological factors.',
    domain: 'psychosocial',
    depth: 0,
    parentId: null,
    children: ['2.1', '2.2', '2.3'],
    scientificallyTestable: true,
    aliases: ['PSH'],
  },

  // --- 2.1 Sociological ---
  {
    id: '2.1',
    label: 'Sociological',
    description: 'Social dynamics, group phenomena, and cultural factors producing UAP reports.',
    domain: 'psychosocial',
    depth: 1,
    parentId: '2',
    children: ['2.1.1', '2.1.2', '2.1.3', '2.1.4', '2.1.5'],
    scientificallyTestable: true,
  },
  {
    id: '2.1.1',
    label: 'Hypnosis',
    description: 'Hypnotic suggestion producing false UAP memories or experiences.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.1.2',
    label: 'Mass Hysteria',
    description: 'Collective delusion or social contagion producing shared UAP reports.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.1.3',
    label: 'Memetic Virus',
    description: 'Self-propagating cultural narratives that generate UAP reports.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.1.4',
    label: 'Conditioning / Disinformation',
    description: 'Deliberate manipulation, propaganda, or psyops creating UAP narratives.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.1.5',
    label: 'Hoax',
    description: 'Deliberate fabrication for attention, profit, or amusement.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.1',
    children: [],
    scientificallyTestable: true,
  },

  // --- 2.2 Psychological ---
  {
    id: '2.2',
    label: 'Psychological',
    description: 'Individual psychological processes producing UAP perceptions.',
    domain: 'psychosocial',
    depth: 1,
    parentId: '2',
    children: ['2.2.1', '2.2.2', '2.2.3', '2.2.4', '2.2.5'],
    scientificallyTestable: true,
  },
  {
    id: '2.2.1',
    label: 'False Belief / Misinterpretation',
    description: 'Cognitive bias or perceptual error leading to misidentification.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.2.2',
    label: 'Fallible / Screen Memory',
    description: 'False or constructed memories obscuring actual events.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.2.3',
    label: 'Psychosomatic Disorder',
    description: 'Physical symptoms produced by psychological distress attributed to UAP.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.2.4',
    label: 'Psychosis / Hallucination',
    description: 'Clinical psychiatric conditions producing UAP perceptions.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.2.5',
    label: 'Collective Unconscious',
    description: 'Jungian archetypes manifesting as UAP experiences across cultures.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.2',
    children: [],
    scientificallyTestable: true,
  },

  // --- 2.3 Neurological ---
  {
    id: '2.3',
    label: 'Neurological',
    description: 'Neurobiological factors producing anomalous perceptions.',
    domain: 'psychosocial',
    depth: 1,
    parentId: '2',
    children: ['2.3.1', '2.3.2', '2.3.3', '2.3.4', '2.3.5'],
    scientificallyTestable: true,
  },
  {
    id: '2.3.1',
    label: 'Psychedelics / Pharmacology',
    description: 'Drug-induced altered states producing UAP-like perceptions.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.3.2',
    label: 'Pathology / Trauma',
    description: 'Brain injury, disease, or trauma producing anomalous perceptions.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.3.3',
    label: 'Neurodivergence',
    description: 'Atypical neural architecture producing enhanced or anomalous perception.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.3.4',
    label: 'High Intuition / Functioning',
    description: 'Heightened perceptual sensitivity or cognitive function.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.3',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '2.3.5',
    label: '"Alien" Implants',
    description: 'Neurological effects attributed to foreign objects or stimulation.',
    domain: 'psychosocial',
    depth: 2,
    parentId: '2.3',
    children: [],
    scientificallyTestable: true,
  },

  // ============================================================
  // DOMAIN 3.0 — METAPHYSICAL
  // ============================================================
  {
    id: '3',
    label: 'Metaphysical',
    description: 'Theories with origins beyond conventional scientific understanding.',
    domain: 'metaphysical',
    depth: 0,
    parentId: null,
    children: ['3.1', '3.2', '3.3'],
    scientificallyTestable: false,
    aliases: ['MPH'],
  },

  // --- 3.1 Paranormal ---
  {
    id: '3.1',
    label: 'Paranormal',
    description: 'Phenomena involving extraordinary human potential or non-material entities.',
    domain: 'metaphysical',
    depth: 1,
    parentId: '3',
    children: ['3.1.1', '3.1.2', '3.1.3', '3.1.4', '3.1.5', '3.1.6'],
    scientificallyTestable: true,
  },
  {
    id: '3.1.1',
    label: 'Psychotronics / Extraordinary Potential',
    description: 'Latent human psychic abilities (telekinesis, remote viewing) producing observable effects.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '3.1.2',
    label: 'NDE / OBE',
    description: 'Near-death or out-of-body experiences suggesting non-physical consciousness.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '3.1.3',
    label: 'Disembodied Spirits / Consciousness',
    description: 'Non-physical conscious entities interacting with physical reality.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '3.1.4',
    label: 'Incorporeal / Bosonic Lifeforms',
    description: 'Entities composed of force-carrier particles or non-baryonic matter.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '3.1.5',
    label: 'Mediumship / Possession',
    description: 'External entities communicating through or controlling human hosts.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.1',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '3.1.6',
    label: 'New Physics',
    description: 'Undiscovered physical laws that explain anomalous phenomena.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.1',
    children: [],
    scientificallyTestable: true,
  },

  // --- 3.2 Occult ---
  {
    id: '3.2',
    label: 'Occult',
    description: 'Hidden knowledge traditions and reality models outside mainstream science.',
    domain: 'metaphysical',
    depth: 1,
    parentId: '3',
    children: ['3.2.1', '3.2.2', '3.2.3', '3.2.4', '3.2.5', '3.2.6'],
    scientificallyTestable: false,
  },
  {
    id: '3.2.1',
    label: 'Hidden Powers of Nature',
    description: 'Esoteric natural forces not yet recognized by science.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.2',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.2.2',
    label: 'Ascended "Masters"',
    description: 'Spiritually evolved beings guiding humanity from higher planes.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.2',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.2.3',
    label: '"Maya" / Sensory Delusion',
    description: 'Physical reality as fundamental illusion (Vedantic/Buddhist ontology).',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.2',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.2.4',
    label: 'Artificial Reality / Matrix Simulation',
    description: 'Reality as a computational simulation with UAP as glitches or features.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.2',
    children: [],
    scientificallyTestable: true,
  },
  {
    id: '3.2.5',
    label: 'Altered / Alternate Reality',
    description: 'Consensus reality as one of many equally valid experiential frames.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.2',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.2.6',
    label: 'Absolute World of Archetypes',
    description: 'Platonic realm of forms manifesting in physical experience.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.2',
    children: [],
    scientificallyTestable: false,
  },

  // --- 3.3 Transcendental ---
  {
    id: '3.3',
    label: 'Transcendental',
    description: 'Religious, spiritual, and theological explanations for UAP.',
    domain: 'metaphysical',
    depth: 1,
    parentId: '3',
    children: ['3.3.1', '3.3.2', '3.3.3', '3.3.4', '3.3.5', '3.3.6'],
    scientificallyTestable: false,
  },
  {
    id: '3.3.1',
    label: '"Gaia" / Nature Spirits',
    description: 'Animistic intelligence of the Earth or natural world.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.3',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.3.2',
    label: 'Angelic Beings',
    description: 'Benevolent spiritual entities from monotheistic traditions.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.3',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.3.3',
    label: '"Djinn" / Neutral Powers',
    description: 'Morally neutral spiritual entities (Islamic jinn, fae folk, trickster spirits).',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.3',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.3.4',
    label: 'Demonic Forces',
    description: 'Malevolent spiritual entities from various religious traditions.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.3',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.3.5',
    label: 'Hierarchy of Being',
    description: 'Neo-Platonic great chain of being with UAP as higher-order entities.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.3',
    children: [],
    scientificallyTestable: false,
  },
  {
    id: '3.3.6',
    label: 'Emanations of Godhead',
    description: 'Direct manifestations of divine creative force or cosmic consciousness.',
    domain: 'metaphysical',
    depth: 2,
    parentId: '3.3',
    children: [],
    scientificallyTestable: false,
  },
];
