import type { BiologicsObservable, BiologicsObservableId } from './types';

export const BIOLOGICS_OBSERVABLES: Record<BiologicsObservableId, BiologicsObservable> = {
  molecular_complexity: {
    id: 'molecular_complexity',
    code: 'BO-1',
    label: 'Molecular Complexity Anomaly',
    description: 'Material exhibits molecular assembly complexity requiring a guided process (life or technology) to produce — molecules with high assembly indices found in abundances impossible through abiotic chemistry.',
    scientificBasis: 'Assembly Theory (Cronin & Walker, Nature 2023). Molecules with molecular assembly index (MA) ≥ 15 in high copy number are statistically impossible without selection or engineering. Provides agnostic biosignature independent of terrestrial biochemistry assumptions.',
    caveat: 'Assembly Theory is an active area of research and remains contested. Critics argue that its assembly index overlaps with established complexity and information measures and that it has not been independently validated as a definitive biosignature. Treat a high assembly index as suggestive rather than conclusive.',
    detectionSignals: [
      'High molecular assembly index (MA ≥ 15) in abundant molecules',
      'Complex molecular structures without known abiotic synthesis pathway',
      'Ordered molecular arrangements exceeding thermodynamic equilibrium expectations',
      'Functional molecular machines or self-assembling structures',
      'Polymeric molecules with non-random sequence information',
    ],
    methods: [
      'Tandem mass spectrometry (MS/MS) for assembly index measurement',
      'Nuclear magnetic resonance (NMR) spectroscopy',
      'Infrared (IR) spectroscopy for functional group identification',
      'High-resolution mass spectrometry for molecular formula determination',
      'Computational assembly pathway analysis',
    ],
    references: [
      'Marshall et al., "Identifying molecules as biosignatures with assembly theory and mass spectrometry," Nature Communications, 2021',
      'Sharma et al., "Assembly Theory Explains and Quantifies Selection and Evolution," Nature, 2023',
    ],
  },
  isotopic_provenance: {
    id: 'isotopic_provenance',
    code: 'BO-2',
    label: 'Non-Terrestrial Isotopic Provenance',
    description: 'Material isotope ratios inconsistent with terrestrial, solar system, or known astrophysical formation processes — indicating extraterrestrial or exotic origin.',
    scientificBasis: 'Isotope ratios serve as fingerprints for nucleosynthetic origin. Terrestrial materials fall within well-characterized ranges. Deviations beyond measurement uncertainty indicate non-terrestrial formation (as demonstrated in meteorite classification).',
    detectionSignals: [
      'Isotope ratios outside terrestrial standard ranges (e.g., δ¹³C, ⁸⁷Sr/⁸⁶Sr)',
      'Non-mass-dependent fractionation patterns',
      'Extinct radionuclide signatures (e.g., ²⁶Al, ⁶⁰Fe) inconsistent with solar system age',
      'Noble gas isotope compositions outside solar wind or planetary ranges',
      'Multi-element isotopic anomalies correlating across sample',
    ],
    methods: [
      'Thermal ionization mass spectrometry (TIMS)',
      'Secondary ion mass spectrometry (SIMS/NanoSIMS)',
      'Multicollector inductively coupled plasma mass spectrometry (MC-ICP-MS)',
      'Noble gas mass spectrometry',
      'Accelerator mass spectrometry (AMS) for rare isotopes',
    ],
    references: [
      'Nittler, "Presolar stardust in meteorites: recent advances and scientific frontiers," Earth and Planetary Science Letters, 2003',
      'McSween & Huss, "Cosmochemistry," Cambridge University Press, 2010',
    ],
  },
  non_standard_biochemistry: {
    id: 'non_standard_biochemistry',
    code: 'BO-3',
    label: 'Non-Standard Biochemistry',
    description: 'Biology uses fundamentally different building blocks than terrestrial life — alternative nucleic acids, non-standard amino acids as backbone, non-carbon scaffolding, or alternative solvent systems.',
    scientificBasis: 'All known terrestrial life shares LUCA biochemistry: DNA/RNA with 4 nucleobases, 20 canonical amino acids, phospholipid membranes, water solvent. Alternative biochemistries have been theorized (XNA, silicon-based, ammonia solvent) but never found naturally on Earth.',
    detectionSignals: [
      'Nucleic acid analogs with non-standard backbone (XNA, TNA, PNA)',
      'Proteins built from non-canonical amino acid sets',
      'Non-phospholipid membrane structures',
      'Silicon-carbon hybrid molecular scaffolds',
      'Metabolic products inconsistent with known biochemical pathways',
      'Information-carrying polymers with non-ACGT/U encoding',
    ],
    methods: [
      'Liquid chromatography-mass spectrometry (LC-MS) for molecular identification',
      'X-ray crystallography for structural determination',
      'Amino acid analysis (chiral and compositional)',
      'Nucleotide sequencing attempts with universal and degenerate primers',
      'Elemental analysis (CHNS/O) for bulk composition',
      'Raman spectroscopy for molecular bond identification',
    ],
    references: [
      'Benner et al., "Alternative Watson-Crick Synthetic Genetic Systems," Cold Spring Harbor Perspectives in Biology, 2016',
      'National Academies, "The Limits of Organic Life in Planetary Systems," 2007',
    ],
  },
  non_phylogenetic_genetics: {
    id: 'non_phylogenetic_genetics',
    code: 'BO-4',
    label: 'Non-Phylogenetic Genetic Signatures',
    description: 'Genetic material falls outside Earth\'s tree of life — sequences with no homology to any known organism, novel genetic codes, or information storage systems incompatible with LUCA-derived biology.',
    scientificBasis: 'All terrestrial organisms share a common ancestor (LUCA) and show phylogenetic relationships via conserved genes (16S/18S rRNA, cytochrome c, etc.). Genetic material that cannot be placed on any branch of the tree of life would indicate independent abiogenesis or non-terrestrial origin.',
    detectionSignals: [
      'DNA/RNA sequences with zero BLAST homology to any known organism',
      'Novel codon usage tables inconsistent with all known genetic codes',
      'Information-encoding molecules that are not DNA or RNA',
      'Genetic regulatory systems without terrestrial analogs',
      'Absence of conserved genes universal to all terrestrial life (e.g., ribosomal RNA)',
    ],
    methods: [
      'Whole genome sequencing (shotgun metagenomics)',
      'BLAST and phylogenetic analysis against NCBI/EBI databases',
      'Codon usage analysis',
      'Ribosomal RNA gene surveys (16S/18S/ITS)',
      'Comparative genomics for conserved gene detection',
      'De novo assembly and annotation',
    ],
    references: [
      'Woese, "The universal ancestor," PNAS, 1998',
      'Cleland & Copley, "The possibility of alternative microbial life on Earth," International Journal of Astrobiology, 2005',
    ],
  },
  anomalous_morphology: {
    id: 'anomalous_morphology',
    code: 'BO-5',
    label: 'Anomalous Morphology',
    description: 'Biological structures exhibit body plans, organ systems, or cellular architectures outside all known phylogenetic trees — morphological features that cannot be derived from any known evolutionary lineage.',
    scientificBasis: 'Terrestrial biology produces morphological diversity within phylogenetic constraints (body plan conservation within phyla, developmental gene toolkit sharing). A biological entity with morphology outside all known phyla would indicate independent evolutionary origin.',
    detectionSignals: [
      'Body plan outside all 33 known animal phyla',
      'Cellular architecture without homology to known cell types',
      'Organ systems with no developmental analog in terrestrial biology',
      'Symmetry patterns not observed in terrestrial organisms',
      'Tissue organization incompatible with known developmental pathways',
      'Biomechanical properties outside known biological material ranges',
    ],
    methods: [
      'Comparative morphological analysis',
      'Histological examination and electron microscopy (SEM/TEM)',
      'Micro-CT scanning for internal structure',
      'Developmental biology analysis (if living specimen)',
      'Biomechanical testing of tissue properties',
      'Phylogenetic morphological matrix analysis',
    ],
    references: [
      'Valentine, "On the Origin of Phyla," University of Chicago Press, 2004',
      'Carroll, "Evo-Devo and an Expanding Evolutionary Synthesis," Cell, 2008',
    ],
  },
  anomalous_bio_interaction: {
    id: 'anomalous_bio_interaction',
    code: 'BO-6',
    label: 'Anomalous Biological Interaction',
    description: 'Agent-level biological interaction that goes beyond simple energetic exposure — demonstrating directed, purposeful, or communicative engagement with biological organisms that implies intelligence or agency.',
    scientificBasis: 'Distinct from Technology Observable TO-6 (Biological Effects), which covers passive radiological/energetic injury from proximity. BO-6 addresses cases where interaction patterns suggest directed agency: selective targeting, behavioral manipulation, tissue sampling, or communication attempts that imply biological intelligence behind the interaction. This is the home for the abduction/experiencer phenomenon and precision animal-tissue removal ("cattle mutilation").',
    caveat: 'Unlike the sensor- and laboratory-grounded observables, this one rests largely on witness and experiencer testimony, and the inference of directed intelligence behind an interaction is not established. Investigations of related phenomena — including the federally funded 1980 Operation Animal Mutilation report — have attributed many cases to mundane causes such as predation. Treat a reported interaction as a prompt for physical corroboration, not as confirmation of agency.',
    caveatLabel: 'Testimony-based — agency not established',
    detectionSignals: [
      'Selective targeting of specific individuals or biological features',
      'Evidence of tissue sampling or biological material collection',
      'Behavioral effects suggesting directed influence (paralysis, compulsion)',
      'Communication attempts through biological channels',
      'Surgical-precision physical interactions with biological tissue',
      'Interaction patterns demonstrating knowledge of target biology',
    ],
    methods: [
      'Forensic medical examination for interaction evidence',
      'Psychological evaluation for behavioral influence markers',
      'Dermatological analysis for precision markings',
      'Toxicological screening for unknown compounds',
      'Neurological assessment for anomalous effects',
      'Comparative analysis across multiple experiencer reports',
    ],
    references: [
      'Mack, "Abduction: Human Encounters with Aliens," Scribner, 1994',
      'Jacobs, "Secret Life: Firsthand Accounts of UFO Abductions," Simon & Schuster, 1992',
      'Rommel, "Operation Animal Mutilation," Report of the District Attorney, First Judicial District, State of New Mexico, 1980',
      'Kelleher & Knapp, "Hunt for the Skinwalker," Paraview Pocket Books, 2005',
    ],
  },
};
